### ISSUE TITLE
Изменения SignUp странички для Accept ToS

### ISSUE THREAD

**Issue by smant** [getsitecontrol/wordpress-plugin#1]
**WORDPRESS**

![image](https://user-images.githubusercontent.com/198931/38200058-8d3a7b6a-369b-11e8-8cb4-93c904627090.png)

Алексей Умилин, [02.04.18 17:29]
В идеале эскиз такой, но можно просто взять новый текст (наверху и внизу) и впаять в существующую страницу

Алексей Умилин, [02.04.18 17:30]
Новый синий - это текущий синий на сайте.

Алексей Умилин, [02.04.18 17:30]
Иконки в полях ввода можно сохранить

**Comment by Alexey-Umilin** [comment]
**ФОРМА РЕГИСТРАЦИИ НА САЙТЕ**

![image](https://user-images.githubusercontent.com/6170639/38200158-ed4511fa-369b-11e8-82b6-33e4a011fd80.png)

У нас три способа регистарции: Фейсбук, Гугл и Имейл. Чтобы любой пользователь согласился с Прайвеси надо либо создать для каждого способа своё окно и там объяснить на что соглашаешься, либо просто на каждую кнопку регистрации на сайте показывать это окно.
